//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.07 at 12:43:28 PM GET 
//


package com.demo.appointments.generated_soap_dto.schedule;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.*;

import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for rule complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="rule"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="start_date" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="end_date" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="doctor_id" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="doctor_specialization" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="appointment_duration" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="slots_amount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rule", propOrder = {
        "startDate",
        "endDate",
        "doctorId",
        "doctorSpecialization",
        "appointmentDuration",
        "slotsAmount"
})
public class Rule {

    @XmlElement(name = "start_date", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar startDate;
    @XmlElement(name = "end_date", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar endDate;
    @XmlElementRef(name = "doctor_id", namespace = "http://www.appointments.demo.com/generated_soap_dto/schedule", type = JAXBElement.class, required = false)
    protected JAXBElement<Long> doctorId;
    @XmlElement(name = "doctor_specialization", required = true)
    protected String doctorSpecialization;
    @XmlElementRef(name = "appointment_duration", namespace = "http://www.appointments.demo.com/generated_soap_dto/schedule", type = JAXBElement.class, required = false)
    protected JAXBElement<Integer> appointmentDuration;
    @XmlElementRef(name = "slots_amount", namespace = "http://www.appointments.demo.com/generated_soap_dto/schedule", type = JAXBElement.class, required = false)
    protected JAXBElement<Integer> slotsAmount;

    /**
     * Gets the value of the startDate property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setStartDate(XMLGregorianCalendar value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the endDate property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setEndDate(XMLGregorianCalendar value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the doctorId property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link Long }{@code >}
     */
    public JAXBElement<Long> getDoctorId() {
        return doctorId;
    }

    /**
     * Sets the value of the doctorId property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link Long }{@code >}
     */
    public void setDoctorId(JAXBElement<Long> value) {
        this.doctorId = value;
    }

    /**
     * Gets the value of the doctorSpecialization property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDoctorSpecialization() {
        return doctorSpecialization;
    }

    /**
     * Sets the value of the doctorSpecialization property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDoctorSpecialization(String value) {
        this.doctorSpecialization = value;
    }

    /**
     * Gets the value of the appointmentDuration property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    public JAXBElement<Integer> getAppointmentDuration() {
        return appointmentDuration;
    }

    /**
     * Sets the value of the appointmentDuration property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    public void setAppointmentDuration(JAXBElement<Integer> value) {
        this.appointmentDuration = value;
    }

    /**
     * Gets the value of the slotsAmount property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    public JAXBElement<Integer> getSlotsAmount() {
        return slotsAmount;
    }

    /**
     * Sets the value of the slotsAmount property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    public void setSlotsAmount(JAXBElement<Integer> value) {
        this.slotsAmount = value;
    }

}
