//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.09 at 06:22:23 AM GET 
//


package org.w3._2001.xmlschema;

import java.time.LocalDateTime;
import jakarta.xml.bind.annotation.adapters.XmlAdapter;

public class Adapter1
    extends XmlAdapter<String, LocalDateTime>
{


    public LocalDateTime unmarshal(String value) {
        return (com.demo.appointments.mapper.SOAPDateTimeAdapter.unmarshal(value));
    }

    public String marshal(LocalDateTime value) {
        return (com.demo.appointments.mapper.SOAPDateTimeAdapter.marshal(value));
    }

}
