//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.09 at 01:22:55 AM GET 
//


package org.w3._2001.xmlschema;

import java.time.LocalTime;
import jakarta.xml.bind.annotation.adapters.XmlAdapter;

public class Adapter2
    extends XmlAdapter<String, LocalTime>
{


    public LocalTime unmarshal(String value) {
        return (com.demo.appointments.mapper.SOAPTimeAdapter.unmarshal(value));
    }

    public String marshal(LocalTime value) {
        return (com.demo.appointments.mapper.SOAPTimeAdapter.marshal(value));
    }

}
