//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.09 at 06:22:23 AM GET 
//


package org.w3._2001.xmlschema;

import java.time.LocalDate;
import jakarta.xml.bind.annotation.adapters.XmlAdapter;

public class Adapter3
    extends XmlAdapter<String, LocalDate>
{


    public LocalDate unmarshal(String value) {
        return (com.demo.appointments.mapper.SOAPDateAdapter.unmarshal(value));
    }

    public String marshal(LocalDate value) {
        return (com.demo.appointments.mapper.SOAPDateAdapter.marshal(value));
    }

}
