//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.04 at 12:57:38 PM GET 
//


package com.demo.appointments.schedule_generator;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;

import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the com.demo.appointments.scehdule package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@SuppressWarnings("unused")
@XmlRegistry
public class ObjectFactory {

    private static final QName _SlotPatientId_QNAME = new QName("http://www.appointments.demo.com/scehdule", "patient_id");
    private static final QName _RuleDoctorId_QNAME = new QName("http://www.appointments.demo.com/scehdule", "doctor_id");
    private static final QName _RuleSlotsAmount_QNAME = new QName("http://www.appointments.demo.com/scehdule", "slots_amount");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema
     * derived classes for package: com.demo.appointments.schedule_generator
     */
    public ObjectFactory() {
        // Auto-generated
    }

    /**
     * Create an instance of {@link ScheduleRequest}
     */
    public ScheduleRequest createScheduleRequest() {
        return new ScheduleRequest();
    }

    /**
     * Create an instance of {@link Rule}
     */
    public Rule createRule() {
        return new Rule();
    }

    /**
     * Create an instance of {@link ScheduleResponse}
     */
    public ScheduleResponse createScheduleResponse() {
        return new ScheduleResponse();
    }

    /**
     * Create an instance of {@link Schedule}
     */
    public Schedule createSchedule() {
        return new Schedule();
    }

    /**
     * Create an instance of {@link Slot}
     */
    public Slot createSlot() {
        return new Slot();
    }

    /**
     * Create an instance of {@link JAXBElement}{@code <}{@link String}{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement}{@code <}{@link String}{@code >}
     */
    @XmlElementDecl(namespace = "http://www.appointments.demo.com/scehdule",
            name = "patient_id", scope = Slot.class)
    public JAXBElement<String> createSlotPatientId(String value) {
        return new JAXBElement<>(_SlotPatientId_QNAME, String.class, Slot.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.appointments.demo.com/scehdule",
            name = "doctor_id", scope = Rule.class)
    public JAXBElement<String> createRuleDoctorId(String value) {
        return new JAXBElement<>(_RuleDoctorId_QNAME, String.class, Rule.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.appointments.demo.com/scehdule",
            name = "slots_amount", scope = Rule.class)
    public JAXBElement<Integer> createRuleSlotsAmount(Integer value) {
        return new JAXBElement<>(_RuleSlotsAmount_QNAME, Integer.class, Rule.class, value);
    }

}
