//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.04 at 12:57:38 PM GET 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.appointments.demo.com/scehdule",
        elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.demo.appointments.schedule_generator;
