//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.07 at 12:43:28 PM GET 
//


package com.demo.appointments.generated_soap_dto.shifts;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;

import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the com.demo.appointments.generated_soap_dto.shifts package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ConditionPeriod_QNAME = new QName("http://www.appointments.demo.com/generated_soap_dto/shifts", "period");
    private final static QName _ConditionTimeStart_QNAME = new QName("http://www.appointments.demo.com/generated_soap_dto/shifts", "time_start");
    private final static QName _ConditionTimeEnd_QNAME = new QName("http://www.appointments.demo.com/generated_soap_dto/shifts", "time_end");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.demo.appointments.generated_soap_dto.shifts
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ShiftRequest }
     */
    public ShiftRequest createShiftRequest() {
        return new ShiftRequest();
    }

    /**
     * Create an instance of {@link Condition }
     */
    public Condition createCondition() {
        return new Condition();
    }

    /**
     * Create an instance of {@link ShiftResponse }
     */
    public ShiftResponse createShiftResponse() {
        return new ShiftResponse();
    }

    /**
     * Create an instance of {@link ShiftList }
     */
    public ShiftList createShiftList() {
        return new ShiftList();
    }

    /**
     * Create an instance of {@link Shift }
     */
    public Shift createShift() {
        return new Shift();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.appointments.demo.com/generated_soap_dto/shifts", name = "period", scope = Condition.class)
    public JAXBElement<String> createConditionPeriod(String value) {
        return new JAXBElement<String>(_ConditionPeriod_QNAME, String.class, Condition.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.appointments.demo.com/generated_soap_dto/shifts", name = "time_start", scope = Condition.class)
    public JAXBElement<Integer> createConditionTimeStart(Integer value) {
        return new JAXBElement<Integer>(_ConditionTimeStart_QNAME, Integer.class, Condition.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.appointments.demo.com/generated_soap_dto/shifts", name = "time_end", scope = Condition.class)
    public JAXBElement<Integer> createConditionTimeEnd(Integer value) {
        return new JAXBElement<Integer>(_ConditionTimeEnd_QNAME, Integer.class, Condition.class, value);
    }

}
