//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.09 at 01:22:55 AM GET 
//


package com.demo.appointments.generated_soap_dto.shifts;

import java.time.LocalTime;
import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.w3._2001.xmlschema.Adapter2;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.demo.appointments.generated_soap_dto.shifts package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ConditionTimeStart_QNAME = new QName("http://www.appointments.demo.com/generated_soap_dto/shifts", "time_start");
    private final static QName _ConditionTimeEnd_QNAME = new QName("http://www.appointments.demo.com/generated_soap_dto/shifts", "time_end");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.demo.appointments.generated_soap_dto.shifts
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ShiftRequest }
     * 
     */
    public ShiftRequest createShiftRequest() {
        return new ShiftRequest();
    }

    /**
     * Create an instance of {@link Condition }
     * 
     */
    public Condition createCondition() {
        return new Condition();
    }

    /**
     * Create an instance of {@link ShiftResponse }
     * 
     */
    public ShiftResponse createShiftResponse() {
        return new ShiftResponse();
    }

    /**
     * Create an instance of {@link ShiftElement }
     * 
     */
    public ShiftElement createShiftElement() {
        return new ShiftElement();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LocalTime }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link LocalTime }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.appointments.demo.com/generated_soap_dto/shifts", name = "time_start", scope = Condition.class)
    @XmlJavaTypeAdapter(Adapter2 .class)
    public JAXBElement<LocalTime> createConditionTimeStart(LocalTime value) {
        return new JAXBElement<LocalTime>(_ConditionTimeStart_QNAME, LocalTime.class, Condition.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LocalTime }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link LocalTime }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.appointments.demo.com/generated_soap_dto/shifts", name = "time_end", scope = Condition.class)
    @XmlJavaTypeAdapter(Adapter2 .class)
    public JAXBElement<LocalTime> createConditionTimeEnd(LocalTime value) {
        return new JAXBElement<LocalTime>(_ConditionTimeEnd_QNAME, LocalTime.class, Condition.class, value);
    }

}
