//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.07 at 12:43:28 PM GET 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.appointments.demo.com/generated_soap_dto/shifts", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.demo.appointments.generated_soap_dto.shifts;
