//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.07 at 12:43:28 PM GET 
//


package com.demo.appointments.generated_soap_dto.shifts;

import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="shift" type="{http://www.appointments.demo.com/generated_soap_dto/shifts}shiftList"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "shift"
})
@XmlRootElement(name = "shiftResponse")
public class ShiftResponse {

    @XmlElement(required = true)
    protected ShiftList shift;

    /**
     * Gets the value of the shift property.
     *
     * @return possible object is
     * {@link ShiftList }
     */
    public ShiftList getShift() {
        return shift;
    }

    /**
     * Sets the value of the shift property.
     *
     * @param value allowed object is
     *              {@link ShiftList }
     */
    public void setShift(ShiftList value) {
        this.shift = value;
    }

}
